# Generated by Django 4.1.7 on 2023-03-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_owner_user_is_public_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_public',
        ),
    ]
