version: "3.9"

volumes:
  postgres_data:

services:

  django:
    build:
     context: ./core
     dockerfile: ./docker/Dockerfile
    image: simple_django
    container_name: simple_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/dev.env
      - ./.envs/postgres.env
    ports:
      - "8000:8000"
    command: /django-commands.sh
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: simple_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/postgres.env
    expose:
      - "5432"
    ports:
      - "5433:5432" #dbeaver port